library(ggplot2)
library(tidyr)
library(gridExtra)
alpha <- read.table("alpha_facet.txt", header=T, row.names= 1, sep="\t")
theme_set(theme_bw())
p1 <- ggplot(alpha, aes(x=Cave, y=observed_otus, color=Cave)) + geom_boxplot(alpha=1, outlier.size=0, size=0.7, width=0.5, fill="transparent") +  geom_jitter( position=position_jitter(0.17), size=1, alpha=0.7) + labs(x="Cave", y="Observed OTUs") + theme(axis.text.x = element_text(angle = 45,vjust = 1,hjust = 1)) + facet_wrap(~ Sample_Type,scales = "free", ncol = 2) + theme(legend.position = "none")
p2 <- ggplot(alpha, aes(x=Cave, y=shannon, color=Cave)) + geom_boxplot(alpha=1, outlier.size=0, size=0.7, width=0.5, fill="transparent") +  geom_jitter( position=position_jitter(0.17), size=1, alpha=0.7) + labs(x="Cave", y="Shannon indices") + theme(axis.text.x = element_text(angle = 45,vjust = 1,hjust = 1)) + facet_wrap(~ Sample_Type,scales = "free", ncol = 2)
p <- grid.arrange(p1,p2,widths=c(0.95,1))
ggsave(p,filename = "observed_otus&shannon.pdf",width = 10,height = 4)
